name: Deploy Preview to Vercel

on:
  push:
    branches:
      - develop

jobs:
  deploy_preview:
    name: Deploy to Vercel (Preview)
    runs-on: ubuntu-latest
    if: github.repository == 'seong-hui/JEOLLOGA-CLIENT'
    steps:
      - name: Checkout develop
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel (Preview)
        run: vercel --token=${{ secrets.VERCEL_TOKEN }} --prod=false --yes
